name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-php@v2
        with:
          php-version: '8.2'
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist
          npm install
      - name: Copy env
        run: cp .env.example .env
      - name: Run tests
        run: vendor/bin/phpunit --testsuite Unit --testsuite Functional || vendor/bin/phpunit
